# 1.find()                在字符串中查找子串，返回第一次出现的索引位置，找不到返回-1      s.find()
# 2.count()                统计子串在字符串中出现的次数                              s.count()
# 3.upper()                 将字符串中所有的字母转换为大写                             s.upper()
# 4,lower()                 将字符串中所有的字母转换为大写                              s.lower()
# 5.split()                 将字符串按照指定分隔符分割成列表表                            s.split()
# 6.strip()                  去除字符串两端的空白字符或指定字符                           s.strop()
# 7,replace()                将字符产中指定字符串替换为新的子串                            s.replace()
# 8.startswith()              检查字符串是否以指定子串开头返回布尔值                      s.startwith()